### ISSUE TITLE
mirror autokit.apk 

### ISSUE THREAD

**Issue by selihc** [harrylepotter/carplay-receiver#1]
Hey, started fiddling with some carplay stuff, just trying to get this code up and running, the autokit apk (from carlinkkit) seems to download agonizingly slowly. Do you think mirroring it (either in this repo, or elsewhere) could be a decent idea?

**Comment by harrylepotter** [comment]
Heya, not sure whether mirroring it elsewhere would be legal. 4x4shop.ca mirrors the last decent version of it, though

**Comment by selihc** [comment]
ah true. it finally downloaded for me! got most things working, too. I've started working on a port to Go for better performance, inspired a lot by this code and your decompiled apk gists. Hoping I can get audio all sorted, as that's the biggest issue with a Sony XAV-AX7000 head unit I have - it crashes fairly often when the audio bitrates change and leave me without carplay for a while.

**Comment by harrylepotter** [comment]
ah nice! Yeah the audio stuff on this project could definitely benefit from some extra work. At the moment i'm using a separate mpv thread to play it back.  I've been meaning to get around to it- Would definitely benefit from directly writing to something like libalsa so that you can accomodate changes in bitrate for things like phone calls and siri
